coverage:
  status:
    project:
      default:
        target: auto
        threshold: 20%
        base: auto 
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false

fixes:
  - "/home/runner/work/workflows/workflows/::"
