[build-system]
requires = ["mesonpep517"]
build-backend = "mesonpep517.buildapi"

[tool.mesonpep517.metadata]
author = "Micron Technology, Inc."
summary = "Fast key-value storage for SSDs and persistent memory"
description = """\
	Python bindings to HSE's C API. \
    HSE is an embeddable key-value store designed for SSDs based on NAND \
    flash or persistent memory. HSE optimizes performance and endurance by \
    orchestrating data placement across DRAM and multiple classes of SSDs \
    or other solid-state storage. HSE is ideal for powering NoSQL, \
    Software-Defined Storage (SDS), High-Performance Computing (HPC), \
    Big Data, Internet of Things (IoT), and Artificial Intelligence (AI) \
    solutions.\
"""
classifiers = [
	"License :: OSI Approved :: Apache Software License",
	"Operating System :: POSIX :: Linux",
	"Programming Language :: Cython",
	"Programming Language :: Python :: 3 :: Only",
	"Topic :: Database",
	"Topic :: Database :: Database Engines/Servers",
	"Typing :: Typed",
]
requires-python = ">=3.6"
homepage = "https://github.com/hse-project/hse-python"
project-urls = [
	"HSE, https://github.com/hse-project/hse",
	"Issue Tracker, https://github.com/hse-project/hse-python",
]
module = "hse"
