name: Bug Reports
description: Create a bug report to help us improve the project.
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for opening an issue. Please be sure to review our [contribution guidelines](CONTRIBUTING.md)
  - type: textarea
    id: bug-description
    attributes:
      label: Description
      description: Also tell us, what did you expect to happen?
      placeholder: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        <!-- 1. Build and install from master
        2. Configure your system
        3. Run some commands
        4. See error in logs -->
