name: Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
              ref: 'hsemaster'
      - name: Install Dependency
        run: |
               sudo apt-get install build-essential libtool pkg-config openjdk-8-jdk libmicrohttpd-dev liburcu-dev libyaml-dev liblz4-1 liblz4-dev curl python3-setuptools gcovr
               sudo apt-get install libmongoc-1.0-0 libbson-1.0-0 libssl-dev libsasl2-dev
               python3 -m pip install --user setuptools_rust wheel
               python3 -m pip install --user poetry
               poetry install
      - name: Test
        run: |
               sed -i.bak "s,ssh://git@bitbucket.micron.com/hse/hse-python.git,https://${{ secrets.GH_TOKEN }}@github.com/bhaveshvasandani/hse-python.git,g" subprojects/hse-python.wrap
               poetry run meson builddir -Dycsb=true -Dinstall-tools=true -Dinstall-configs=true -Db_coverage=true -Doptimization=0
               poetry run meson test -C builddir --suite=unit
               poetry run meson compile -C builddir gcovr-xml
      - name: Upload
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          file: builddir/coverage.xml 
          verbose: true
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
              name: coverage-artifact
              path: builddir/ 
