name: Validate Builds

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  build1:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
        build_type: [release, debugoptimized]

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential libbsd-dev pkg-config libmicrohttpd-dev liburcu-dev libyaml-dev libcurl4-openssl-dev python3-setuptools

    - uses: actions/checkout@v2
      with:
        ref: hse-pythontest

    - name: Setup python environment to run branch
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip3 install wheel
        pip3 install -r requirements.txt
        pip3 install meson ninja

    - name: Build, compile and test hse-python
      run: |
        source venv/bin/activate
        meson builddir -Dwerror=true
        ninja -C builddir
        meson test -C builddir --print-errorlogs --no-stdsplit

    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: build-artifact
        path: builddir/meson-logs/

  format-check:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
        build_type: [release, debugoptimized]

    steps:
    - uses: actions/checkout@v2
      with:
        ref: hse-pythontest

    - name: install dependency
      run: |
        python3 -m pip install black

    - name: Black format check
      continue-on-error: true
      run: |
        black --check ./