name: Validate Builds

on:
        push:
        pull_request:
                types: [opened, synchronize, reopened, edited]

jobs:
        build:
                runs-on: ${{ matrix.os }}
                strategy:
                        fail-fast: false
                        matrix:
                                os: [ubuntu-18.04]
                                build_type: [release, debugoptimized, debug]

                steps:
                - name: Install dependencies
                  run: |
                          sudo apt-get install build-essential libblkid-dev gettext autopoint autoconf bison libtool pkg-config openjdk-8-jdk libmicrohttpd-dev liburcu-dev libyaml-dev liblz4-1 liblz4-dev curl python3-setuptools 
                          python3 -m pip install --user setuptools_rust wheel
                          python3 -m pip install --user poetry
                - uses: actions/checkout@v2
                  with:
                          ref: 'hsemaster'
                - name: Setup python environment to run branch
                  run: |
                          poetry install

                - name: Build setup with YCSB, tools and configs
                  run: |
                          sed -i.bak "s,ssh://git@bitbucket.micron.com/hse/hse-python.git,https://${{ secrets.GH_TOKEN }}@github.com/bhaveshvasandani/hse-python.git,g" subprojects/hse-python.wrap
                          echo "BUILD=${{ matrix.build_type }}"
                          poetry shell
                          lsblk
                          df -h
                          meson builddir -Dbuildtype=${{ matrix.build_type }} -Dycsb=true -Dinstall-tools=true -Dinstall-configs=true -Dwerror=true -Dtests=all

                - name: Clang format check
                  continue-on-error: true
                  run: |
                          poetry shell
                          meson -C builddir format-check

                - name: Run Unit tests
                  continue-on-error: true
                  run: |
                          poetry shell
                          meson test -C builddir --no-suite smoke --no-suite long --print-errorlogs --no-stdsplit

