name: Validate PR

on:
        push:
        pull_request:
                types: [opened, synchronize, reopened, edited]

jobs:
        branch-check:
                runs-on: ubuntu-18.04

                continue-on-error: true

                steps:
                - uses: actions/checkout@v2
                  with:
                          ref: 'libmpool'

        build:
                runs-on: ${{ matrix.os }}
                needs: [branch-check]
                strategy:
                        fail-fast: false
                        matrix:
                                os: [ubuntu-18.04]
                                build_type: [release, debugoptimized, debug]

                steps:
                - name: Install dependencies
                  run: |
                          sudo apt-get install build-essential libblkid-dev gettext autopoint autoconf bison libtool pkg-config openjdk-8-jdk libmicrohttpd-dev liburcu-dev libyaml-dev liblz4-1 liblz4-dev curl
                - uses: actions/checkout@v2
                  with:
                          ref: 'libmpool'
                - name: Setup python environment to run branch
                  run: |
                          python3 -m venv venv
                          source venv/bin/activate
                          pip3 install wheel
                          pip3 install -r requirements.txt
                          pip3 install meson ninja

                - name: Build setup with YCSB, tools and configs
                  run: |
                          sed -i.bak "s,ssh://git@bitbucket.micron.com/hse/hse-python.git,https://${{ secrets.GH_TOKEN }}@github.com/bhaveshvasandani/hse-python.git,g" subprojects/hse-python.wrap
                          echo "BUILD=${{ matrix.build_type }}"
                          source venv/bin/activate
                          meson builddir -Dbuildtype=${{ matrix.build_type }} -Dycsb=true -Dinstall-tools=true -Dinstall-configs=true -Dwerror=true

                - name: Clang format check
                  continue-on-error: true
                  run: |
                          source venv/bin/activate
                          meson -C builddir format-check

                - name: Run Unit tests
                  continue-on-error: true
                  run: |
                          source venv/bin/activate
                          meson test -C builddir --print-errorlogs --no-stdsplit

