name: Validate Builds

on:
        push:
        pull_request:
                types: [opened, synchronize, reopened, edited]

jobs:
        build1:

                runs-on: ${{ matrix.os }}
                strategy:
                        fail-fast: false
                        matrix:
                                os: [ubuntu-18.04]
                                build_type: [release]

                steps:
                - name: Install dependencies
                  run: |  

                          sudo apt-get update
                          sudo apt-get install build-essential libblkid-dev libbsd-dev gettext autopoint autoconf bison libtool pkg-config openjdk-8-jdk libmicrohttpd-dev liburcu-dev libyaml-dev liblz4-1 liblz4-dev curl python3-setuptools
                          dpkg -l | grep curl
                          sudo apt-get install libmongoc-1.0-0 libbson-1.0-0 libssl-dev libsasl2-dev

                - uses: actions/checkout@v2
                  with:
                          ref: 'hse-pythontest'

                - name: Setup python environment to run branch
                  run: |
                          python3 -m venv venv
                          source venv/bin/activate
                          pip3 install wheel
                          pip3 install black
                          pip3 install -r requirements.txt
                          pip3 install meson ninja

                - name: Build hse-python
                  run: |  
                          source venv/bin/activate
                          meson builddir -Dtests=true
                
                - name: Black format check
                  continue-on-error: true
                  run: |
                          black --check ./

                - name: Run Unit tests
                  run: |
                          source venv/bin/activate
                          meson test -C builddir --print-errorlogs --no-stdsplit


                - uses: actions/upload-artifact@v2
                  if: failure()
                  with:
                    name: build-artifact
                    path: builddir/meson-logs/

