name: Validate Builds

on:
        push:
        pull_request:
                types: [opened, synchronize, reopened, edited]

jobs:
        build:
                runs-on: ubuntu-18.04

                steps:
                - name: Install dependencies
                  run: |

                          sudo apt-get install build-essential libblkid-dev gettext autopoint autoconf bison libtool pkg-config openjdk-8-jdk libmicrohttpd-dev liburcu-dev libyaml-dev liblz4-1 liblz4-dev curl
                - uses: actions/checkout@v2
                  with:
                          ref: 'hsemaster'

                - name: Setup python environment to run branch
                  run: |
                          python3 -m venv venv
                          source venv/bin/activate
                          pip3 install wheel
                          pip3 install -r requirements.txt
                          pip3 install meson ninja
                
                - name: Install Hse
                  run: |
                          source venv/bin/activate
                          meson builddir -Dbuildtype=release -Dycsb=true -Dinstall-tools=true -Dinstall-configs=true -Dtests=all -Dwerror=true
                          meson install -C builddir

                - uses: actions/checkout@v2
                  with:
                          ref: 'hse-pythonmaster'

                - name: Install requirements to run hse-python branch
                  run: |
                          source venv/bin/activate
                          pip3 install -r requirements.txt
                
                - name: Build hse-python
                  run: |
                          source venv/bin/activate
                          meson builddir -Dbuildtype=release -Dtests=true -Dwerror=true

                - name: Run Unit tests
                  run: |
                          source venv/bin/activate
                          meson test -C builddir --print-errorlogs --no-stdsplit


                - uses: actions/upload-artifact@v2
                  if: failure()
                  with:
                    name: build-artifact
                    path: builddir/meson-logs/

